### ISSUE TITLE
Example for single page app

### ISSUE THREAD

**Issue by flip111** [agrafix/funblog#10]
Would be nice if the funblog also some some features that are needed for a single page app. Such as serving a static html from file and some REST endpoints.

**Comment by flip111** [comment]
@agrafix to get me started could you provide a code snippet how to serve a static file?

**Comment by agrafix** [comment]
You can either use a middleware ( https://github.com/agrafix/funblog/blob/65c2b41019ae3a3bd04a2ffb92e028f167295c7d/src/Web/Blog.hs#L87 ), or the http://hackage.haskell.org/package/Spock-core-0.12.0.0/docs/Web-Spock-Action.html#v:file combinator.

**Comment by flip111** [comment]
Thank you @agrafix i guess the middleware is the fastest way to serve static files but maybe less configurable per file since it looks in a path?
