### ISSUE TITLE
Why is this not production ready?

### ISSUE THREAD

**Issue by chrissound** [agrafix/funblog#12]
> Please note that this software is NOT intendet to be used in production (yet?).

It would be useful to know why - potential security issues? Unknown unknowns?

**Comment by agrafix** [comment]
It's basically just a reminder that this was written to show case writing Haskell web apps with Spock and not to provide a fully working blog software. This reduces expectations and hopefully frustrations. Nevertheless, I don't directly see any reasons not to use it for a personal blog for example.

**Comment by chrissound** [comment]
It's probably more production ready then Wordpress though! Personally I don't think we should discredit it. Anyway, thanks for making this! :+1:
