### ISSUE TITLE
Won't compile on Ubuntu 14.04, ghc-7.8.3

### ISSUE THREAD

**Issue by dschalk** [agrafix/funblog#3]
cabal: Could not resolve dependencies:
trying: funblog-0.1.1.0 (user goal)
trying: base-4.7.0.1/installed-e4b... (dependency of funblog-0.1.1.0)
next goal: HSmarty (dependency of funblog-0.1.1.0)
rejecting: HSmarty-0.2.0.1, 0.2.0.0, 0.1.1.0, 0.1.0.0 (conflict:
base==4.7.0.1/installed-e4b..., HSmarty => base==4.6.*)
Dependency tree exhaustively searched.

**Comment by agrafix** [comment]
It should compile now
