### ISSUE TITLE
Missing field in record construction 

### ISSUE THREAD

**Issue by codygman** [agrafix/funblog#6]
```
~/programming/haskell/spock-example $ git clone git@github.com:agrafix/funblog.git
~/programming/haskell/spock-example $ cd funblog
~/programming/haskell/spock-example/funblog $ cabal install
~/programming/haskell/spock-example/funblog $ ./.cabal-sandbox/bin/funblog 
Spock is running on port 8080
```

In my web browser I navigate to http://localhost:8080/ and click login, and it says "something went wrong". I see the following in the shell where I'm running funblog:

```
src/Web/Blog.hs:(59,11)-(65,11): Missing field in record construction Web.Spock.Internal.Types.sc_sessionExpandTTL
```

**Comment by wiria** [comment]
Starting from 0.7.8.0, SessionCfg have a new field (sc_sessionExpandTTL). 
So you need to add that field.

**Comment by agrafix** [comment]
Exactly. And the dependency bounds would need to be set correctly. If you want you can send a pull request, otherwise I will fix that tomorrow.

**Comment by codygman** [comment]
It looks only adding sc_sessionExpandTTL was necessary for it to compile
with GHC 7.8.3. Can't now, but will send PR if I can later.
