### ISSUE TITLE
upgrade lts

### ISSUE THREAD

**Issue by flip111** [agrafix/funblog#9]
Could the lts-5.8 please be upgraded to a newer release? I like to have an example of spock which uses ghc 8 and more recent packages.

**Comment by agrafix** [comment]
Sure! Would you like to send a PR?

**Comment by flip111** [comment]
I would like to but at the moment it's not possible because I have no clue how Spock works and I wanted to use this funblog to learn.

**Comment by agrafix** [comment]
Here you go: https://github.com/agrafix/funblog/commit/e555e6bd9d1595f674b90766ec572042a5076dae

Hope that helps

**Comment by flip111** [comment]
Thank you very much, i verified it works well !
